#!/bin/sh
# Emit a Homebrew formula that installs the released binaries.
#
#   generate-formula.sh <version> <owner/repo> <dir-with-release-artifacts>
#
# The artifact directory must hold the .sha256 files dist produces beside
# each archive. dist builds and publishes everything else; only the formula
# is ours, because its template cannot declare a launchd/systemd service.
set -eu

version="$1"
repo="$2"
artifacts="$3"
base="https://github.com/${repo}/releases/download/v${version}"

# Read every checksum up front: a command substitution inside the heredoc
# below cannot abort this script, so a missing file there would silently
# yield a formula with an empty sha256.
sha() {
    file="${artifacts}/lastpass-ssh-agent-$1.tar.xz.sha256"
    if [ ! -s "$file" ]; then
        echo "missing or empty checksum for $1: $file" >&2
        exit 1
    fi
    tr -d "[:space:]" < "$file"
}

macos_arm="$(sha aarch64-apple-darwin)"
macos_intel="$(sha x86_64-apple-darwin)"
linux_arm="$(sha aarch64-unknown-linux-musl)"
linux_intel="$(sha x86_64-unknown-linux-musl)"

# The template is a quoted heredoc: nothing in it is expanded, so backticks
# in the caveats cannot run as commands and $VAR cannot leak the builder's
# environment into a published formula. Values are substituted afterwards.
cat <<'FORMULA' | sed \
    -e "s|@VERSION@|${version}|g" \
    -e "s|@REPO@|${repo}|g" \
    -e "s|@BASE@|${base}|g" \
    -e "s|@MACOS_ARM@|${macos_arm}|g" \
    -e "s|@MACOS_INTEL@|${macos_intel}|g" \
    -e "s|@LINUX_ARM@|${linux_arm}|g" \
    -e "s|@LINUX_INTEL@|${linux_intel}|g"
# Generated by packaging/homebrew/generate-formula.sh — do not edit by hand.
class LastpassSshAgent < Formula
  desc "SSH agent backed by the LastPass CLI: keys never persist on disk"
  homepage "https://github.com/@REPO@"
  version "@VERSION@"
  license "MIT"

  depends_on "lastpass-cli"

  on_macos do
    on_arm do
      url "@BASE@/lastpass-ssh-agent-aarch64-apple-darwin.tar.xz"
      sha256 "@MACOS_ARM@"
    end
    on_intel do
      url "@BASE@/lastpass-ssh-agent-x86_64-apple-darwin.tar.xz"
      sha256 "@MACOS_INTEL@"
    end
  end

  on_linux do
    on_arm do
      url "@BASE@/lastpass-ssh-agent-aarch64-unknown-linux-musl.tar.xz"
      sha256 "@LINUX_ARM@"
    end
    on_intel do
      url "@BASE@/lastpass-ssh-agent-x86_64-unknown-linux-musl.tar.xz"
      sha256 "@LINUX_INTEL@"
    end
  end

  def install
    bin.install "lastpass-ssh-agent"
  end

  # `brew services start lastpass-ssh-agent` installs this as a launchd user
  # agent on macOS and a systemd user unit on Linux — same declaration, both
  # platforms. std_service_path_env puts Homebrew's bin on PATH so the agent
  # can find lpass, which a bare launchd/systemd environment would not.
  service do
    run [opt_bin/"lastpass-ssh-agent", "start"]
    keep_alive true
    log_path var/"log/lastpass-ssh-agent.log"
    error_log_path var/"log/lastpass-ssh-agent.log"
    environment_variables PATH: std_service_path_env
  end

  def caveats
    <<~EOS
      Log in to LastPass first, then check the setup:

        lpass login you@example.com
        lastpass-ssh-agent doctor

      Run it in the background (launchd on macOS, systemd --user on Linux):

        brew services start lastpass-ssh-agent

      It then starts again at every login. Homebrew does not restart running
      services on upgrade, so after `brew upgrade` the old binary keeps
      serving until the next login unless you restart it yourself:

        brew services restart lastpass-ssh-agent

      On Linux a --user service only runs while you have a session. To keep
      the agent up without one:

        loginctl enable-linger "$USER"

      Do NOT use `sudo brew services`: as a system daemon the agent has no
      GUI session, so every confirmation prompt fails closed and no signature
      is ever approved.

      On Linux the default confirmation mode is "tty", which a background
      service has no terminal for. Set an askpass helper in
      ~/.config/lastpass-ssh-agent/config.toml before starting the service:

        confirm = "askpass"
        askpass = "/usr/bin/ssh-askpass"

      Point SSH at the agent. The socket path differs per platform, so take
      it from the agent rather than guessing:

        lastpass-ssh-agent env

      and put that path in ~/.ssh/config:

        Host *
            IdentityAgent "<the path printed above>"

      Note that IdentityAgent overrides SSH_AUTH_SOCK for the hosts it matches.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lastpass-ssh-agent --version")
    # doctor exits nonzero without a LastPass login, but must still run
    assert_match "lpass", shell_output("#{bin}/lastpass-ssh-agent doctor 2>&1", 1)
  end
end
FORMULA
